// White-box adversarial zero-list regression for Buthe's verifier (37.a1).
//
// Math (Buthe, arXiv:1308.6704, Thm 3.3 + Lemma 3.4): for an entire L-function
// the verifier's statistic S(h) = W_f + W_infinity - W_s equals the f-hat
// weighted contribution of the zeros MISSING from the supplied list, and that
// weight Re f-hat is strictly positive on the strip. So exact S(h) >= 0 always;
// the verifier confirms when the whole S-ball is < threshold (0.49 / 0.98), and
// flags a strictly-negative S-ball as a hard over-count (ERR_BUT_ERROR).
//
// Baseline: clean 37.a1 is accepted, every grid S(h) is not strictly negative,
//   and the library's first zero matches the independent PARI ordinate below.
// Missing-zero mutation: drop a low stored zero (gamma < buthe_b); its f-hat is
//   > 0.49, so S rises above threshold => ERR_RH_ERROR (NOT success, NOT
//   over-count).
// Duplicate-zero mutation: insert a second copy of a low zero; the extra f-hat
//   (~1.0 well inside [-b,b]) drives S strictly negative => ERR_BUT_ERROR.
//
// Independent reference (5fn.1), regenerated by the git-excluded
// artifacts/research/buthe-reference/gen_37a1_reference.py and embedded here:
//   provenance: PARI lfunzeros + explicit fhat through SageMath 10.8
//   (PARI 2.17), command in the script header.
//   first positive zero gamma_0(37.a1) = 5.003170014006658696
//   fhat(gamma_0) at (b=32,h=8) = 0.99998...  (duplicate subtracts ~1 from S)
//   fhat(b)       at (b=32,h=8) = 0.49999...  (Lemma 3.4 missed-zero floor)
#define REF_FIRST_ZERO_37A1 "5.003170014006658696"

#include <assert.h>
#include <inttypes.h>
#include <stdio.h>
#include <flint/acb_poly.h>
#include "glfunc.h"
#include "glfunc_internals.h"

// 37.a1: ainvs [0,0,1,-1,0]. Bad prime 37 has local factor 1 + T (LMFDB
// {37,{1,1}}; in the 1 - a_p T convention that is a_37 = -1).
static long mod_p37(long v, long p) { return ((v % p) + p) % p; }

static long ap_37(long P) {
  long c = 1;
  for (long x = 0; x < P; x++) {
    long x3 = mod_p37(x * mod_p37(x * x, P), P);
    long rhs = mod_p37(x3 - x, P);
    for (long y = 0; y < P; y++)
      if (mod_p37(mod_p37(y * y, P) + y, P) == rhs)
        c++;
  }
  return P + 1 - c;
}

static void cb(acb_poly_t poly, uint64_t p, int d, int64_t prec, void *pm) {
  (void)d; (void)prec; (void)pm;
  acb_poly_zero(poly);
  long P = (long)p;
  if (P == 37) {
    acb_poly_set_coeff_si(poly, 0, 1);
    acb_poly_set_coeff_si(poly, 1, 1);
    return;
  }
  long a = ap_37(P);
  acb_poly_set_coeff_si(poly, 0, 1);
  acb_poly_set_coeff_si(poly, 1, -a);
  acb_poly_set_coeff_si(poly, 2, P);
}

static Lfunc_t make_37a1(void) {
  Lerror_t ec = ERR_SUCCESS;
  double mus[2] = {0, 1};
  Lfunc_t LL = Lfunc_init(2, 37, 0.5, mus, &ec);
  if (fatal_error(ec) || !LL) {
    fprintf(stderr, "Lfunc_init failed: ");
    fprint_errors(stderr, ec);
    return NULL;
  }
  assert(Lfunc_set_rh_method(LL, LFUNC_RH_BUTHE) == ERR_SUCCESS);

  ec |= Lfunc_use_all_lpolys(LL, cb, NULL);
  if (!fatal_error(ec))
    ec |= Lfunc_compute(LL);

  if (fatal_error(ec)) {
    fprintf(stderr, "37.a1 compute failed: ");
    fprint_errors(stderr, ec);
    Lfunc_clear(LL);
    return NULL;
  }
  if ((ec & ERR_RH_ERROR) || (ec & ERR_BUT_ERROR)) {
    fprintf(stderr, "37.a1 baseline compute ecode=0x%lx\n", (unsigned long)ec);
    Lfunc_clear(LL);
    return NULL;
  }
  return LL;
}

static uint64_t zero_count(Lfunc *L) {
  uint64_t n = 0;
  while (n < MAX_ZEROS && !arb_is_zero(L->zeros[0][n]))
    n++;
  return n;
}

static void require_low_zero(Lfunc *L) {
  assert(!arb_is_zero(L->zeros[0][0]));
  assert(arb_lt(L->zeros[0][0], L->buthe_b));
}

static int check_baseline(void) {
  Lfunc_t LL = make_37a1();
  if (!LL)
    return 2;
  Lfunc *L = (Lfunc *)LL;
  require_low_zero(L);

  int ok = 1;

  // 5fn.1 cross-check: the library's first positive zero must overlap the
  // independent PARI ordinate (widened by a generous absolute tolerance well
  // above the printed precision of the embedded constant).
  {
    arb_t zref;
    arb_init(zref);
    arb_set_str(zref, REF_FIRST_ZERO_37A1, L->wprec);
    arb_add_error_2exp_si(zref, -40);  // ~9e-13, >> the 18-digit constant's error
    if (!arb_overlaps(L->zeros[0][0], zref)) {
      fprintf(stderr, "FAIL: first zero disagrees with PARI reference %s\n",
              REF_FIRST_ZERO_37A1);
      ok = 0;
    }
    assert(arb_overlaps(L->zeros[0][0], zref));
    arb_clear(zref);
  }

  arb_t S;
  arb_init(S);
  for (int i = 0; i < BUTHE_NH; i++) {
    buthe_S_at(S, L, i, L->wprec);
    if (arb_is_negative(S)) {
      fprintf(stderr, "FAIL: baseline S(h) is strictly negative at grid %d\n", i);
      ok = 0;
    }
    assert(!arb_is_negative(S));
  }

  Lerror_t be = buthe_check_RH(L);
  printf("baseline buthe_check_RH = 0x%lx\n", (unsigned long)be);
  if (be != ERR_SUCCESS) {
    fprintf(stderr, "FAIL: baseline Buthe verdict is not ERR_SUCCESS\n");
    ok = 0;
  }
  assert(be == ERR_SUCCESS);

  arb_clear(S);
  Lfunc_clear(LL);
  return ok ? 0 : 1;
}

static int check_missing_zero(void) {
  Lfunc_t LL = make_37a1();
  if (!LL)
    return 2;
  Lfunc *L = (Lfunc *)LL;
  require_low_zero(L);

  uint64_t n = zero_count(L);
  assert(n >= 2);
  for (uint64_t i = 0; i + 1 < MAX_ZEROS; i++)
    arb_set(L->zeros[0][i], L->zeros[0][i + 1]);

  Lerror_t be = buthe_check_RH(L);
  printf("missing-zero buthe_check_RH = 0x%lx\n", (unsigned long)be);
  int ok = 1;
  if (be == ERR_SUCCESS) {
    fprintf(stderr, "FAIL: missing-zero mutation returned ERR_SUCCESS\n");
    ok = 0;
  }
  if ((be & ERR_RH_ERROR) == 0) {
    fprintf(stderr, "FAIL: missing-zero mutation did not set ERR_RH_ERROR\n");
    ok = 0;
  }
  if (be & ERR_BUT_ERROR) {
    fprintf(stderr, "FAIL: missing-zero mutation set ERR_BUT_ERROR\n");
    ok = 0;
  }
  assert(be != ERR_SUCCESS);
  assert((be & ERR_RH_ERROR) != 0);
  assert((be & ERR_BUT_ERROR) == 0);

  Lfunc_clear(LL);
  return ok ? 0 : 1;
}

static int check_duplicate_zero(void) {
  Lfunc_t LL = make_37a1();
  if (!LL)
    return 2;
  Lfunc *L = (Lfunc *)LL;
  require_low_zero(L);

  uint64_t n = zero_count(L);
  assert(n + 1 < MAX_ZEROS);
  for (uint64_t i = n + 1; i > 1; i--)
    arb_set(L->zeros[0][i], L->zeros[0][i - 1]);
  arb_set(L->zeros[0][1], L->zeros[0][0]);

  Lerror_t be = buthe_check_RH(L);
  printf("duplicate-zero buthe_check_RH = 0x%lx\n", (unsigned long)be);
  int ok = 1;
  if ((be & ERR_BUT_ERROR) == 0) {
    fprintf(stderr, "FAIL: duplicate-zero mutation did not set ERR_BUT_ERROR\n");
    ok = 0;
  }
  assert((be & ERR_BUT_ERROR) != 0);

  Lfunc_clear(LL);
  return ok ? 0 : 1;
}

int main(void) {
  int rc = 0;
  rc |= check_baseline();
  rc |= check_missing_zero();
  rc |= check_duplicate_zero();
  if (rc)
    return 1;
  printf("PASS: Buthe distinguishes clean, missing, and duplicated low zeros for 37.a1.\n");
  return 0;
}
