// High-degree L-function regression driver (bead lfunctions-8dz).
//
// Reads one object (generated by test/highdeg/gen.py) and asserts the numerical
// outputs against golden values (LMFDB for degree 2/4, Pari lfunsympow for the
// symmetric powers). Exit code is the oracle: 0 = all assertions passed.
//
// Certified vs golden regression: the library certifies only rank 0/1 (see
// Lfunc_rank). These asserts always demand the golden rank/zeros match, but that
// is a certified claim only for a rank-0/1 row with no tolerated warning. A
// rank > 1 row (or a tolerate_rh row) is a golden regression comparison: it must
// still match LMFDB/Pari, but rank > 1 is outside what Lfunc_rank certifies, so
// passing the warning gate below does not make it a certified rank claim.
//
// Input file (see test/highdeg/INTERFACES.md sec B):
//   line 1: degree conductor normalisation self_dual
//   line 2: mu_0 ... mu_{degree-1}
//   line 3: EXPECT rank eps_re eps_im z1 z1_err taylor taylor_err tolerate_rh
//             (taylor == "NA" => skip the leading-Taylor assertion)
//   line p: p c0 c1 ... c_degree     (local L-poly coeffs, ascending, decimal strings)
//
// With only lines 1-2 present (no EXPECT, no factors) it prints the library's
// Lfunc_nmax and exits 0 — used by gen.py to size the Euler-factor request.
#include <cstdint>
#include <cstdio>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <flint/fmpz.h>
#include <flint/fmpz_poly.h>
#include <flint/acb_poly.h>
#include <primesieve.hpp>
#include "glfunc.h"
#include "sym_power.h"

static int g_fail = 0;
static void check(bool ok, const char *name, const std::string &detail) {
  printf("  [%s] %s %s\n", ok ? "PASS" : "FAIL", name, detail.c_str());
  if (!ok) g_fail = 1;
}

struct factor_row {
  uint64_t p;
  std::vector<std::string> toks;
};

// arb ref from decimal string, widened by absolute error `err`
static void ref_arb(arb_t ref, const std::string &s, double err, slong prec) {
  arb_set_str(ref, s.c_str(), prec);
  arb_t e; arb_init(e); arb_set_d(e, err);
  arb_add_error(ref, e); arb_clear(e);
}

int main(int argc, char **argv) {
  if (argc < 2) { fprintf(stderr, "usage: %s input\n", argv[0]); return 2; }
  std::ifstream in(argv[1]);
  std::string line;
  const slong prec = 400;

  std::getline(in, line);
  std::stringstream s1(line);
  uint64_t degree = 0, conductor = 0; double norm = 0; int self_dual = 1;
  s1 >> degree >> conductor >> norm >> self_dual;
  // Optional 5th token "sympow": the good-prime lines then carry only the base
  // curve's a_p, and this driver forms the degree-(k+1) Sym^k factor itself via
  // sym_power_lpoly (k = degree - 1). When the token is absent the extraction
  // leaves xform empty, so form_sympow is false and every factor is explicit.
  std::string xform; s1 >> xform;
  const bool form_sympow = (xform == "sympow");
  const int sym_k = (int) degree - 1;
  if (degree == 0 || degree > MAX_DEGREE || conductor == 0) {
    fprintf(stderr, "malformed input (degree=%lu conductor=%lu) — generator likely failed\n",
            degree, conductor);
    return 2;
  }

  std::getline(in, line);
  std::stringstream s2(line);
  std::vector<double> mus(degree);
  for (auto &m : mus) s2 >> m;

  // Public advanced init so self-duality is declared up front instead of poking
  // the opaque handle. Mirrors Lfunc_init's defaults (target_prec=DEFAULT and
  // gprec=0 keep the G-cache active, see src/g.c); Lfunc_init_advanced copies
  // Lp.mus, so the local vector suffices, and cache_dir outlives the Lfunc.
  Lerror_t ec = 0;
  char cache_dir[] = ".";
  Lparams_t Lp;
  Lp.degree = degree;
  Lp.conductor = conductor;
  Lp.normalisation = norm;
  Lp.mus = mus.data();
  Lp.target_prec = DEFAULT_TARGET_PREC;
  Lp.wprec = 0;
  Lp.gprec = 0;
  Lp.self_dual = self_dual ? YES : DK;
  Lp.rank = DK;
  Lp.cache_dir = cache_dir;
  Lfunc_t L = Lfunc_init_advanced(&Lp, &ec);
  if (fatal_error(ec)) { fprint_errors(stderr, ec); return 1; }
  uint64_t nmax = Lfunc_nmax(L);

  // EXPECT line (optional — absent => nmax query)
  int exp_rank = -1, tolerate_rh = 0;
  double eps_re = 0, eps_im = 0, z1_err = 0, taylor_err = 0;
  std::string z1s, taylors = "NA";
  bool have_expect = false;
  std::streampos after_mus = in.tellg();
  if (std::getline(in, line)) {
    std::stringstream s3(line);
    std::string kw; s3 >> kw;
    if (kw == "EXPECT") {
      have_expect = true;
      s3 >> exp_rank >> eps_re >> eps_im >> z1s >> z1_err >> taylors >> taylor_err >> tolerate_rh;
    } else {
      in.seekg(after_mus);  // line was a factor; rewind
    }
  }

  std::vector<factor_row> rows;
  while (std::getline(in, line)) {
    if (line.empty()) continue;
    std::stringstream ss(line);
    uint64_t p; ss >> p;
    if (p > nmax) continue;
    std::vector<std::string> toks; std::string tok;
    while (ss >> tok) toks.push_back(tok);
    rows.push_back({p, toks});
  }
  std::sort(rows.begin(), rows.end(), [](const factor_row &a, const factor_row &b) {
    return a.p < b.p;
  });
  for (size_t i = 1; i < rows.size(); i++) {
    if (rows[i - 1].p == rows[i].p) {
      fprintf(stderr, "duplicate local factor row for p=%lu\n", (unsigned long)rows[i].p);
      Lfunc_clear(L);
      return 2;
    }
  }
  if (rows.empty()) {
    if (have_expect) {
      fprintf(stderr, "missing local factor rows for EXPECT-bearing input\n");
      Lfunc_clear(L);
      return 2;
    }
    printf("nmax=%lu\n", nmax);
    Lfunc_clear(L);
    return 0;
  }
  {
    primesieve::iterator ps;
    size_t idx = 0;
    for (uint64_t expected = ps.next_prime(); expected <= nmax; expected = ps.next_prime()) {
      if (idx >= rows.size()) {
        fprintf(stderr, "missing local factor row for p=%lu (need every prime <= nmax=%lu)\n",
                (unsigned long)expected, (unsigned long)nmax);
        Lfunc_clear(L);
        return 2;
      }
      if (rows[idx].p != expected) {
        if (rows[idx].p < expected)
          fprintf(stderr, "unexpected local factor row for non-prime/out-of-order p=%lu (expected p=%lu)\n",
                  (unsigned long)rows[idx].p, (unsigned long)expected);
        else
          fprintf(stderr, "missing local factor row for p=%lu before p=%lu (need every prime <= nmax=%lu)\n",
                  (unsigned long)expected, (unsigned long)rows[idx].p, (unsigned long)nmax);
        Lfunc_clear(L);
        return 2;
      }
      idx++;
    }
    if (idx != rows.size()) {
      fprintf(stderr, "unexpected extra local factor row for p=%lu above nmax=%lu\n",
              (unsigned long)rows[idx].p, (unsigned long)nmax);
      Lfunc_clear(L);
      return 2;
    }
  }

  acb_poly_t poly; acb_poly_init(poly);
  fmpz_t z; fmpz_init(z);
  acb_t c; acb_init(c);
  uint64_t count = 0;
  for (const factor_row &row : rows) {
    uint64_t p = row.p;
    const std::vector<std::string> &toks = row.toks;
    acb_poly_zero(poly);
    if (form_sympow && toks.size() == 1) {
      // base a_p only: form the Sym^k good-prime factor here, exact fmpz -> acb
      fmpz_set_str(z, toks[0].c_str(), 10);
      // A base a_p must satisfy the Hasse bound a_p^2 <= 4p (checked in fmpz to
      // avoid overflow). A value outside it is not a trace (e.g. a mis-padded bad
      // factor whose leading coefficient landed on a one-token line), so fail
      // loudly instead of silently forming a wrong Sym^k factor. This also subsumes
      // the slong-range check: any Hasse-valid a_p fits a slong.
      {
        fmpz_t aa, fourp; fmpz_init(aa); fmpz_init(fourp);
        fmpz_mul(aa, z, z);                                  // a_p^2
        fmpz_set_ui(fourp, p); fmpz_mul_ui(fourp, fourp, 4); // 4p
        const bool hasse_ok = (fmpz_cmp(aa, fourp) <= 0);
        fmpz_clear(aa); fmpz_clear(fourp);
        if (!hasse_ok) {
          fprintf(stderr, "sympow base a_p=%s violates the Hasse bound at p=%lu (corrupt input)\n",
                  toks[0].c_str(), (unsigned long) p);
          acb_poly_clear(poly); fmpz_clear(z); acb_clear(c); Lfunc_clear(L);
          return 2;
        }
      }
      fmpz_poly_t f; fmpz_poly_init(f);
      sym_power_lpoly(f, fmpz_get_si(z), p, sym_k);
      const slong d = fmpz_poly_degree(f);
      for (slong j = 0; j <= d; j++) {
        fmpz_poly_get_coeff_fmpz(z, f, j);
        acb_set_fmpz(c, z);
        acb_poly_set_coeff_acb(poly, j, c);
      }
      fmpz_poly_clear(f);
    } else {
      // explicit local-factor coefficients (ascending): good ec/genus2/cmf primes
      // and all bad primes, including sympow's
      for (uint64_t i = 0; i < toks.size(); i++) {
        fmpz_set_str(z, toks[i].c_str(), 10);
        acb_set_fmpz(c, z);
        acb_poly_set_coeff_acb(poly, i, c);
      }
    }
    Lfunc_use_lpoly(L, p, poly);
    count++;
  }

  ec |= Lfunc_compute(L);
  printf("degree=%lu conductor=%lu nmax=%lu primes=%lu\n", degree, conductor, nmax, count);

  // (0) no fatal error; certification caveats only when explicitly tolerated.
  // NB this is a warning gate (RH/zero reliability), not a rank-range gate: a
  // rank > 1 row passes it but is a golden regression comparison, since Lfunc_rank
  // certifies only rank 0/1.
  check(!fatal_error(ec), "no-fatal", "");
  // ERR_DBL_ZERO and ERR_SOME_DATA directly compromise zero completeness /
  // reliability (an unresolved stationary point / a possible double zero, and
  // data running out of precision before the end of the Turing zone), so they
  // block a certified rank/zero claim exactly like the RH/short-supply bits.
  // This is the full caveat set documented for Lfunc_rank / Lfunc_zeros.
  const Lerror_t cert_blockers =
      ERR_INSUFF_EULER | ERR_RH_ERROR | ERR_RH_UNAVAILABLE |
      ERR_NO_RANK | ERR_CONFLICT_RANK | ERR_DBL_ZERO | ERR_SOME_DATA;
  const Lerror_t tolerated = tolerate_rh ? ERR_RH_ERROR : ERR_SUCCESS;
  {
    std::stringstream d;
    d << "ecode=" << ec;
    check((ec & (cert_blockers & ~tolerated)) == 0, "certification-warnings", d.str());
  }
  if (!tolerate_rh)
    check((ec & ERR_RH_ERROR) == 0, "rh-confirmed", "ERR_RH_ERROR must be absent");
  else if (ec & ERR_RH_ERROR)
    printf("  [note] ERR_RH_ERROR present (tolerated for degree>=3; bead lfunctions-0zo)\n");

  if (have_expect) {
    // (1) rank
    int64_t r = Lfunc_rank(L);
    { std::stringstream d; d << "got " << r << " want " << exp_rank;
      check(r == exp_rank, "rank", d.str()); }

    // (2) |eps| = 1  and  eps overlaps (eps_re, eps_im)
    arb_t mag, one; arb_init(mag); arb_init(one);
    acb_abs(mag, Lfunc_sign(L), prec);
    arb_set_ui(one, 1); { arb_t e; arb_init(e); arb_set_d(e, 1e-9); arb_add_error(one, e); arb_clear(e); }
    check(arb_overlaps(mag, one), "|eps|=1", "");
    acb_t epsref; acb_init(epsref); acb_set_d_d(epsref, eps_re, eps_im);
    { arb_t e; arb_init(e); arb_set_d(e, 1e-9); acb_add_error_arb(epsref, e); arb_clear(e); }
    check(acb_overlaps(Lfunc_sign(L), epsref), "eps-value", "");
    arb_clear(mag); arb_clear(one); acb_clear(epsref);

    // (3) first zero
    arb_t zref; arb_init(zref); ref_arb(zref, z1s, z1_err, prec);
    check(arb_overlaps(Lfunc_zeros(L, 0) + 0, zref), "first-zero", z1s);
    arb_clear(zref);

    // (4) leading Taylor coeff (optional)
    if (taylors != "NA") {
      arb_t tref; arb_init(tref); ref_arb(tref, taylors, taylor_err, prec);
      check(arb_overlaps(Lfunc_Taylor(L), tref), "taylor", taylors);
      arb_clear(tref);
    } else {
      printf("  [skip] taylor (not provided)\n");
    }
  }

  fprintf(stderr, "ecode: "); fprint_errors(stderr, ec);
  acb_poly_clear(poly); fmpz_clear(z); acb_clear(c); Lfunc_clear(L);
  return g_fail;
}
